# shell conf
shell zsh

# cursor
cursor_shape block
cursor_shape_unfocused block
cursor #cf75eb
cursor_text_shape block
cursor_blink_interval 0
cursor_trail 6
cursor_text_color #ffffff

# font
font_size 12
font_family family="mesloLGL Nerd Font"


# window layout
remember_window_size  no
initial_window_width  1400
initial_window_height 800
window_margin_width 8

# window config
background_opacity 0.8
background #000000
